Fix issues #14
mezzio/mezzio-router pull request #15
Opened 2021-01-07 19:07 UTC by nepster-web

https://github.com/mezzio/mezzio-router/issues/14

2021-01-07 19:16 UTC, samsonasik commented on src/RouteCollectorFactory.php
> +        $config = (array)$container->get('config');
probably better with instanceof `ArrayObject` check, eg:

```suggestion
        $config = $container->get('config');
        $config = $config instanceof \ArrayObject
            ? $config->getArrayCopy()
            : $config;
```

2021-01-07 19:41 UTC, nepster-web commented on src/RouteCollectorFactory.php
> +        $config = (array)$container->get('config');
If we support a common interface, the implementation may be different. 
so, maybe other implementations will implement custom collections, like: MyArrayWrapper or ArrayIterator and etc.

If we use `$config instanceof \ArrayObject` we will close only 2 case: with simple array and ArrayObject.

2021-01-08 00:52 UTC, Ocramius commented on src/RouteCollectorFactory.php
> +        $config = (array)$container->get('config');
Array casts on objects are not usage of object public API, and expose object internals in unintentional ways. Operating with the `ArrayAccess` API (and checking for that type) is more correct here.

2021-01-08 09:57 UTC, samsonasik commented
there is no method `getArrayCopy` in `ArrayAccess`, also, please provide unit test

2021-01-08 09:57 UTC, nepster-web commented on src/RouteCollectorFactory.php
> +        $config = (array)$container->get('config');
@Ocramius, I fixed its like @samsonasik proposed, however with ArrayAccess.

2021-01-08 09:59 UTC, nepster-web commented
@samsonasik, fair. working on it

2021-01-08 10:32 UTC, Ocramius approved these changes
LGTM.

Just an additional note: since this is a bugfix, let's target `3.3.x` instead of `3.4.x`

2021-01-08 10:35 UTC, nepster-web commented
@samsonasik 
https://github.com/mezzio/mezzio-router/blob/050022a8e0982a2dec0347f484bd5639fd7fded3/test/RouteCollectorFactoryTest.php#L90

https://github.com/mezzio/mezzio-router/blob/050022a8e0982a2dec0347f484bd5639fd7fded3/src/RouteCollectorFactory.php#L61

We solve a specific problem with ArrayObject. as you suggested.

2021-01-08 10:46 UTC, Ocramius commented on src/RouteCollectorFactory.php
> +        $config = $config instanceof ArrayObject
Ah, just noticed that we check for `ArrayObject` specifically: IMO better to check for `ArrayAccess` and then use `offsetExists` explicitly, but not really that attached to that opinion too strongly.

2021-01-08 10:50 UTC, nepster-web commented on src/RouteCollectorFactory.php
> +        $config = $config instanceof ArrayObject
I think this will require more changes for getDetectDuplicatesFlag method.

2021-01-08 13:56 UTC, samsonasik commented
please apply DCO https://github.com/mezzio/mezzio-router/pull/15/checks?check_run_id=1668060328

2021-01-08 17:00 UTC, nepster-web commented
@samsonasik, DCO interesting thing. I didn't know about it.

2021-01-11 21:24 UTC, nepster-web commented
@samsonasik, what do you think about the release?

2021-01-15 00:32 UTC, samsonasik commented
There is 1 travis build failure https://travis-ci.com/github/mezzio/mezzio-router/jobs/469882033

could you verify? Thank you.

2021-01-15 12:56 UTC, nepster-web commented
@samsonasik, @Ocramius  check it please. 
The analyzer doesn't like code duplication and doesn't understand data types.

2021-01-15 13:03 UTC, samsonasik approved these changes

2021-03-19 03:51 UTC, guilhermeaiolfi commented
Shouldn't this be merged and released?

2021-04-19 07:55 UTC, Ocramius requested changes

2021-04-19 07:55 UTC, Ocramius commented on src/RouteCollectorFactory.php
> +        $config = is_array($config) ? new ArrayObject($config) : $config;
IMO should be simplified by removing the need for `ArrayObject` at all: we can `assert($config instanceof ArrayAccess || is_array($config))` instead.

2021-04-19 07:55 UTC, Ocramius commented on src/RouteCollectorFactory.php
> +        if (! $config instanceof ArrayAccess) {
Can be dropped based on assertion

2021-04-19 17:45 UTC, nepster-web reviewed
good too

2021-05-13 19:29 UTC, merged