Optimize route addition
mezzio/mezzio-router pull request #3
Opened 2020-02-10 18:05 UTC by nightlinus

|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | no
| BC Break      | yes
| New Feature   | no
| RFC           | no
| QA            | no

### Description

This pr optimizes route addition by removing O(n) duplicate check. In case of big monolitic application this starts to bite performance of application initialization. I have moved duplication check to separate class because now it owns hashmap data structure for searching route.

Solves #1

2020-02-10 20:14 UTC, geerteltink commented
Just wondering what router you are using. If you need speed you may want to look into FastRoute and it's caching support: https://docs.mezzio.dev/mezzio/v3/features/router/fast-route/#fastroute-caching-support

2020-02-15 18:40 UTC, nightlinus commented
> Just wondering what router you are using. If you need speed you may want to look into FastRoute and it's caching support: https://docs.mezzio.dev/mezzio/v3/features/router/fast-route/#fastroute-caching-support

I am using Aura. Thank you for FastRoute caching link, but i should mention that its caching doesn't bypass `RouteCollector` calls and duplication check. I am working on caching routes in my application and there is some problem that as for now routes collection can be taken only from `RouteCollector` and `getRoutes()` is not part of `RouterInterface` so we have 2 places that actually must contain all routes and 2 places to restore from cache, but this is not the case for this pr.

2020-06-16 21:55 UTC, weierophinney requested changes
I rebased for you - please pull before making additional changes.

I've noted one change - if you get that in place, I think this will be ready to merge!

2020-06-16 21:55 UTC, weierophinney commented on src/RouteCollector.php
>      }
```suggestion
    public function __construct(RouterInterface $router, ?DuplicateRouteDetector $duplicateRouteDetector = null)
    {
        $this->router = $router;
        $this->duplicateRouteDetector = $duplicateRouteDetector ?: new DuplicateRouteDectector();
    }
```

Since it has no constructor arguments, making it nullable and providing a default will keep BC for end-users.

2020-06-16 21:56 UTC, weierophinney commented
Also, @nightlinus — check the travis failures.

2020-06-17 12:51 UTC, nightlinus commented
done

2020-06-22 20:04 UTC, weierophinney requested changes

2020-06-22 20:04 UTC, weierophinney commented on src/RouteCollector.php
> +        $this->duplicateRouteDetector = $duplicateRouteDetector ?? new DuplicateRouteDetector();
Since `DuplicateRouteDetector` is marked `final`, and has no dependencies, couldn't we omit the constructor argument for it, and just leave this line?

```suggestion
    public function __construct(RouterInterface $router)
    {
        $this->router = $router;
        $this->duplicateRouteDetector = new DuplicateRouteDetector();
```

2020-06-22 20:04 UTC, weierophinney commented on test/RouteCollectorTest.php
> +        $this->collector = new RouteCollector($this->router->reveal(), new DuplicateRouteDetector());
If we make the change I suggest previously, this can be reverted.

2020-06-22 20:04 UTC, weierophinney commented on test/RouteCollectorTest.php
> +        $this->collector = new RouteCollector($this->router->reveal(), new DuplicateRouteDetector());
Same remark here.

2020-07-22 15:42 UTC, 10n commented on src/RouteCollector.php
> +        $this->duplicateRouteDetector = new DuplicateRouteDetector();
Why don't you move this in  `RouteCollectorFactory`  ?

Also, I suggest you implement an interface, make it invokable  and also create an alias in ConfigProvider.
This would allow any developer to use it as a service and also override it with a local implementation.

2020-07-22 17:02 UTC, nightlinus commented on src/RouteCollector.php
> +        $this->duplicateRouteDetector = new DuplicateRouteDetector();
This is BC break as was suggested by @weierophinney

2020-09-09 14:42 UTC, nightlinus commented
Is there something else i should fix before merging @weierophinney ?

2020-09-10 06:31 UTC, samsonasik commented
@geerteltink could you give reason for closing this PR? or it was an accidentally hit close PR button?

2020-09-10 06:44 UTC, geerteltink commented
I did not close it. I'm adding automatic releases according the guide. I guess it got automatically closed when removing develop via cli. If I go over the `reopen and comment` button it says develop branch was removed.

We should revise the workflow and delete the develop and master branch as last, after rebasing all open PRs.

/cc @weierophinney

2020-09-10 06:52 UTC, geerteltink commented
@nightlinus I cannot reopen or rebase your MR. Can you rebase it onto branch `3.2.x` and see if you can reopen this MR?

2020-10-22 11:36 UTC, pine3ree commented on src/RouteCollector.php
> +        $this->duplicateRouteDetector = new DuplicateRouteDetector();
I agree, for another reason, about the factory. (I am not sure about the need for an interface for this task, but not against it)
IMO the duplicateRouteDetector instance should also be allowed to be passed in (and to be) null (via factory-(dev|prod)-configuration), thus skipping duplicate checks. Developers should be allowed to control when actually perform it, e.g. in dev-mode only. A default ALWAYS-ON value would not cause any BC break. Kind regards.

2020-11-01 09:57 UTC, Dragomeat commented on src/RouteCollector.php
>      public function __construct(RouterInterface $router)
```suggestion
    public function __construct(RouterInterface $router, DuplicateRouteDetector $duplicateRouteDetector = null)
```

2020-11-01 09:57 UTC, Dragomeat commented on src/RouteCollector.php
> +        $this->duplicateRouteDetector = new DuplicateRouteDetector();
```suggestion
        $this->duplicateRouteDetector = $duplicateRouteDetector ?? new DuplicateRouteDetector();
```

2020-11-05 14:30 UTC, nightlinus commented
Fellows, i dont understand what should i do to help this merged or declined. I have done edits as was suggested by @weierophinney, now i get reviews in different directions. Can someone help me to understand what should i do with this PR please? @geerteltink @samsonasik @boesing

2021-01-06 15:31 UTC, weierophinney commented on src/RouteCollector.php
> +        $this->duplicateRouteDetector = new DuplicateRouteDetector();
While I agree about the idea of the factory, for BC purposes, it _does_ need to be enabled by default _at the constructor level_, not at the factory level. If a consumer had decided to create their own factory for the route collector previously, they would not know to pass the `DuplicateRouteDetector` instance, and would thus end up in a scenario where duplicate detection is disabled after updating the library within the same major version.

What we _can_ do is use a flag here. Since the logic is marked `final`, we can have a flag that defaults to `true`, indicating the `DuplicateRouteDetector` should be used. Users who want to _disable_ it would pass a boolean `false` for the flag during instantiation of the `RouteCollector`, which would disable that.

We can then also add a config flag for the factory to consume in order to disable it.

This would address the BC concerns, as well as the concerns that developers have a way to disable it for production.

I'm working on that now, @nightlinus ; no need for you to do more work than you already have on this!

2021-01-06 16:06 UTC, weierophinney approved these changes

2021-01-06 16:23 UTC, merged