Refine types, reduce psalm baseline
mezzio/mezzio-router pull request #38
Opened 2023-01-11 14:40 UTC by gsteel

|    Q          |   A
|-------------- | ------
| Documentation | yes
| QA            | yes

### Description

Reduces baseline to a handful of issues, type coverage increased to around 99.7%

Closes #39

2023-01-11 15:24 UTC, gsteel commented
I have another patch ready to queue after this one that adds `@final` to _all_ classes.

2023-01-11 22:23 UTC, weierophinney requested changes
Overall makes sense. I've noted a couple themes:

- We may want to consider putting a PSR-11 stub file in a dev package for usage by Psalm so we don't need to recreate it in every package that has a PSR-11 dependency.
- This package dropped the requirement on laminas-zendframework-bridge some time ago, but still has references to ZF classes. Since the goal of this particular patch is to help refine types and reduce the Psalm baseline, removing those references now would help achieve both goals.

2023-01-11 22:23 UTC, weierophinney commented on .psr-container.php.stub
> +namespace Psr\Container {
I'm wondering if we should put this in a dev package somewhere so we can bring it into all the different components that use a PSR-11 container?

2023-01-11 22:23 UTC, weierophinney commented on src/ConfigProvider.php
> +                'Zend\Expressive\Router\RouteCollector' => RouteCollector::class,
This component is no longer depending on the laminas-zendframework-bridge, which means we can remove the above lines entirely!

2023-01-11 22:23 UTC, weierophinney commented on src/Middleware/ImplicitHeadMiddleware.php
> +                ->withAttribute('Zend\Expressive\Router\RouteResult', $routeResult)
This call can be removed (see previous comment).

2023-01-11 22:23 UTC, weierophinney commented on src/Middleware/ImplicitHeadMiddlewareFactory.php
> +            $hasDeprecatedRouter = $container->has('Zend\Expressive\Router\RouterInterface');
We can get rid of this "has deprecated router" logic now.

2023-01-11 22:23 UTC, weierophinney commented on src/Middleware/ImplicitHeadMiddlewareFactory.php
> +                : $container->get('Zend\Expressive\Router\RouterInterface'),
This can just be `$container->get(RouterInterface::class)` now.

2023-01-11 22:23 UTC, weierophinney commented on src/Middleware/RouteMiddleware.php
> +            ->withAttribute('Zend\Expressive\Router\RouteResult', $result);
This can be removed now.

2023-01-11 22:23 UTC, weierophinney commented on src/RouteCollector.php
>      public function __construct(RouterInterface $router, bool $detectDuplicates = true)
Elsewhere you've introduced constructor property promotion where it makes sense; any reason why you didn't here?

2023-01-11 22:23 UTC, weierophinney commented on src/RouteCollectorFactory.php
> +            $hasDeprecatedRouter = $container->has('Zend\Expressive\Router\RouterInterface');
The deprecated router logic can be removed from this factory now.

2023-01-11 22:23 UTC, weierophinney commented on src/Test/AbstractImplicitMethodsIntegrationTest.php
> +    public function withoutImplicitMiddleware(): Generator
Question: why Generator and not iterable? I've tended to go with iterable and then provide a shape in the `@return` annotation, which allows switching between returning an array or returning a generator. Just curious to know what your preference is and why. :smile:

2023-01-11 22:23 UTC, weierophinney commented on test/ConfigProviderTest.php
> +                    'Zend\Expressive\Router\RouteCollector' => RouteCollector::class,
Assuming you make the proposed changes to the `ConfigProvider`, the above lines can be removed.

2023-01-11 22:23 UTC, weierophinney commented on test/Middleware/ImplicitHeadMiddlewareFactoryTest.php
> +            ->withConsecutive([RouterInterface::class], ['Zend\Expressive\Router\RouterInterface'])
Here, too.

2023-01-11 22:23 UTC, weierophinney commented on test/Middleware/ImplicitHeadMiddlewareTest.php
> +                    'Zend\Expressive\Router\RouteResult',
and so on and so forth

2023-01-11 22:23 UTC, weierophinney commented on test/Middleware/RouteMiddlewareTest.php
> +                    'Zend\Expressive\Router\RouteResult',
and in this class as well

2023-01-11 22:23 UTC, weierophinney commented on test/RouteCollectorFactoryTest.php
> +            ->withConsecutive([RouterInterface::class], ['Zend\Expressive\Router\RouterInterface'])
and here

2023-01-11 23:28 UTC, gsteel commented on src/RouteCollector.php
>      public function __construct(RouterInterface $router, bool $detectDuplicates = true)
Missed that one!!

2023-01-11 23:33 UTC, gsteel commented on src/Test/AbstractImplicitMethodsIntegrationTest.php
> +    public function withoutImplicitMiddleware(): Generator
I doesn't really make any difference - In this case, I was just cleaning up the doc block on auto-pilot. I don't have a preference in cases like this, but I tend to prefer more explicit types than `iterable` so that the return type plays nice with `iterator_to_array` or `count` or whatever…

2023-01-11 23:37 UTC, gsteel commented on .psr-container.php.stub
> +namespace Psr\Container {
That's a good idea - It would be a good place for standard templates such as `psalm.xml`, `phpunit.xml.dist` et al.

Would you prefer I revert the addition here and expand the baseline for now?

2023-01-11 23:38 UTC, gsteel commented
Thanks for the review @weierophinney :)

2023-01-12 08:06 UTC, boesing commented on .psr-container.php.stub
> +namespace Psr\Container {
lctrs/psalm-psr-container-plugin

2023-01-12 08:14 UTC, gsteel commented on .psr-container.php.stub
> +namespace Psr\Container {
That's what I use, but @Ocramius has told me off in the past for the extra dep when a stub would do 😁

2023-01-12 13:19 UTC, boesing commented on .psr-container.php.stub
> +namespace Psr\Container {
Sure, but as long as it is a dev-dependency, I dont really care. If we get problems with it, it can still be dropped. Until then, I'll keep using it 🤷🏼‍♂️

2023-01-12 15:05 UTC, weierophinney approved these changes
This looks good - I'll let you decide how to handle the container stub. I prefer we slurp it in from elsewhere, but knowing Marco has suggested otherwise, do what makes you most comfortable.

2023-01-12 15:06 UTC, Ocramius commented
I think keeping the stub duplicated is our best effort, for now: sharing it will only lead to loads of added complexity, for one single file.

We may use a psalm plugin in future, but not for now.

2023-01-12 15:10 UTC, Ocramius approved these changes
Thanks @gsteel!

2023-01-12 15:10 UTC, merged

2023-01-12 15:12 UTC, Ocramius commented
Note: releasing as minor even though there is some BC risk due to dropped aliases.

In theory, those are hamdled by a correct `Zend` to `Laminas` migration