Add PSR-17 Support
mezzio/mezzio-router pull request #48
Opened 2023-03-29 09:15 UTC by gsteel

|    Q          |   A
|-------------- | ------
| BC Break      | yes
| New Feature   | yes

### Description

Replaces all callable parameters and properties with `StreamFactoryInterface` and `ResponseFactoryInterface` where appropriate and removes the callable compatability layer.

Closes #29

2023-03-29 09:23 UTC, froschdesign commented
@gsteel 
The target branch 4.0.x is missing.

2023-03-29 09:29 UTC, gsteel commented
> The target branch 4.0.x is missing.

I'll create the branch if this is approved 👍

2023-03-29 09:33 UTC, boesing commented
Can we please go with the logic as in https://github.com/mezzio/mezzio-authorization/pull/11/files?
Forward compatibility in current major versions should be the goal to reduce the amount of pain when migrating to new majors.
We can fix our internal types in the next major version but until then, providing support for both `callable` and the factory interfaces is doable. There are some caveats (i.e. due to the `aliases` / `delegators` registered in upstream projects - also `initializers` but I forgot these in the other components already) but IMHO worth doing so.

2023-03-29 10:12 UTC, gsteel commented
I'm not sure I understand the point of preserving support for callables @boesing - As this lib is only useful to a Mezzio app, it's most likely that Stream|Response factories are already wired up in the container via Diactoros, making migration a zero effort chore.

The callable response decorator was already deprecated, and I'll have to introduce a callable stream decorator to satisfy `StreamFactoryInterface` which in turn will create a hard dependency on Diactoros' `StreamFactory` so that `createStreamFromFile` etc can be implemented.

I thought that this patch was more about removing support for callables than adding PSR-17 because at least `ResponseFactoryInterface` has been supported for quite a while now???

2023-03-29 10:17 UTC, boesing commented
> I thought that this patch was more about removing support for callables than adding PSR-17 because at least ResponseFactoryInterface has been supported for quite a while now???

It is not supported in this component for quite a while and thus I dont understand why you think it is already supported.
The whole point of introducing PSR-17 is that we provide the possibility from within all the components before we require upstream to provide PSR-17.
Just because you have `laminas/laminas-diactoros` required does not mean that you automatically have its config provider registered (which would be required to have the factory interfaces available via `$container` - or upstream registered manually all the factory interfaces which is most likely not the case as it is not required to do so in mezzio v3). 
Furthermore, diactoros is not required in mezzio, you can use `nyholm/psr7` which ~(AFAIR) does not provide any PSR-17 factories~ provides PSR-17 factories but would require configuration changes to actually register all the factory interfaces to the `nyholm/psr7` PSR-17 factory).

So overall, adding support for both makes sense as a first step while dropping support in next major.
Starting with mezzio v4, I'd expect all components do support PSR-17 as there won't be any callable registered anymore.

But maybe I am missing something, can you probably elaborate why you think that there is already PSR-17 support in this component?


----

So all I want to say is, I spent quite a lot of time in providing proper forward compatibility for PSR-17 so that we can switch to full PSR-17 in the next major. All I want is that we provide compatibility layer in `mezzio-router` v3 so that we can do this change (so the change in this PR) in `mezzio-router` v4.

2023-03-29 11:11 UTC, gsteel commented
@boesing - I reverted the patch and added compatibility for `StreamFactoryInterface` - I was actually targeting 4 here, so I think I understand now that whilst the response factory was already supported here, the stream factory was still outstanding for the 3.x series. I will revert a couple more things here so that this can go into 3.x

2023-03-29 16:20 UTC, boesing requested changes
Works for me, the only thing which might happen is that there are custom factories provided by upstream factories for the `StreamInterface` which could be slightly modified to i.e. decorate the `StreamInterface` by default which won't be the case once the `StreamFactoryInterface` creates the `StreamInterface`.

If you need more input on the problem I try to outline, just let me know.
I guess you can adapt the tests regarding the `ResponseFactoryInterface`, that should outline the issue quite good.

2023-03-29 16:20 UTC, boesing commented on src/Middleware/ImplicitHeadMiddleware.php
> +     * @param callable(): StreamInterface|StreamFactoryInterface $streamFactory A factory capable of returning an empty
I guess you have to surround the callable with brackets as psalm might read it as the return value of the callable.

`callable(): StreamInterface|StreamFactoryInterface` !== `(callable():StreamInterface)|StreamFactoryInterface`

I wonder why psalm is happy with the current notation.

2023-03-29 16:20 UTC, boesing commented on src/Middleware/ImplicitHeadMiddleware.php
> +            $this->streamFactory = function () use ($streamFactory): StreamInterface {
I actually removed the callable functionality from within the other classes which consumed callables.

Can we rewrite this so that the `streamFactory` property only accepts `StreamFactoryInterface`? That would require some `CallableStreamFactory` which implements the `StreamFactoryInterface` of course.

2023-03-29 16:20 UTC, boesing commented on src/Middleware/ImplicitHeadMiddlewareFactory.php
> +        // Prefer StreamFactoryInterface if present over StreamInterface callable
I am not sure if we should prefer it by default. Thats why I added that trait in the other components (and maybe here?) to detect whether or not there are projects implementing custom logic to provide the `StreamInterface`.

Not sure if I can properly phrase the problem, so if you can't follow me here, just let me know.

2023-03-29 16:22 UTC, boesing commented
> the stream factory was still outstanding for the 3.x series

That was probably my fault. I did not properly detected the callable in https://github.com/mezzio/mezzio-router/pull/23 :-/

2023-03-31 09:31 UTC, gsteel commented on src/Middleware/ImplicitHeadMiddleware.php
> +            $this->streamFactory = function () use ($streamFactory): StreamInterface {
I've added a decorator to wrap the callable so that we can type hint on `StreamFactoryInterface` but retained the ability to pass a callable to the constructor. 

The factory now always provides a `StreamFactoryInterface` so I can drop callable from the constructor but what about users providing custom factories? BC break or not?

2023-03-31 09:33 UTC, gsteel commented on src/Middleware/ImplicitHeadMiddlewareFactory.php
> +        // Prefer StreamFactoryInterface if present over StreamInterface callable
Hopefully resolved? Preference is switched back to prefer the callable first.

2023-04-22 23:54 UTC, ghostwriter commented on src/Middleware/ImplicitHeadMiddleware.php
> +    public function __construct(private RouterInterface $router, callable|StreamFactoryInterface $streamFactory)
we should make this `public function __construct(private RouterInterface $router, private StreamFactoryInterface $streamFactory)`.

If users want to use a `callable` they can pass in a `CallableDecorator` that implements `StreamFactoryInterface`.

2023-04-22 23:54 UTC, ghostwriter commented on src/Middleware/ImplicitOptionsMiddleware.php
> +    public function __construct(callable|ResponseFactoryInterface $responseFactory)
we should make this `public function __construct(private ResponseFactoryInterface $responseFactory)`

2023-04-22 23:54 UTC, ghostwriter commented on src/Middleware/MethodNotAllowedMiddleware.php
> +    public function __construct(callable|ResponseFactoryInterface $responseFactory)
we should make this `public function __construct(private ResponseFactoryInterface $responseFactory)`

2023-04-22 23:58 UTC, ghostwriter commented
review is based on the assumption that this PR will target v4.

2023-04-23 07:16 UTC, gsteel commented
@ghostwriter 

> review is based on the assumption that this PR will target v4.

This patch is targeting 3.x - In v4, callable will be dropped along with the decorators

@boesing - when you get a chance, can you review again please?

2023-04-23 20:37 UTC, boesing commented
Can you probably adapt the unit tests from the other PRs we've already created?
I have created some weird edge-case tests to verify we do not oversee something.

2023-04-23 22:24 UTC, gsteel commented
Pretty confident everything is covered - the StreamFactory only has 1 responsibility here and that is to generate an empty stream for implicit HEAD requests.

Perhaps @weierophinney or @Ocramius could review to get this one over the line - we'll need it to get v4 out the door right?

2023-04-24 13:45 UTC, weierophinney approved these changes
Functionality looks sane, and tests cover the changes. :ship:

2023-04-24 14:11 UTC, Ocramius approved these changes
:ship: LGTM, thanks @gsteel!

2023-04-24 14:11 UTC, Ocramius commented on src/Stream/CallableStreamFactoryDecorator.php
> +    /** @inheritDoc */
We should probably document `@returns never`?

2023-04-24 14:11 UTC, Ocramius commented on src/Stream/CallableStreamFactoryDecorator.php
> +    /** @inheritDoc */
We should probably document `@returns never`?

2023-04-24 14:12 UTC, merged